### ISSUE TITLE
TypeError: asciiize() got an unexpected keyword argument 'x_ticks'

### ISSUE THREAD

**Issue by richstokes** [epsylabs/lucyna#1]
When trying to run `ecs service dashboard our-service-name-here -c our-cluster-name-here`

Just curious if you'd seen this before?

**Comment by richstokes** [comment]
```
Traceback (most recent call last):
  File "/Users/rich/.pyenv/versions/3.8.7/bin/lucyna", line 8, in <module>
    sys.exit(safe_cli())
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/cli.py", line 22, in safe_cli
    cli()
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/plugins/ecs/service/commands.py", line 22, in dashboard
    LiveRunner(
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/runner.py", line 24, in run
    with Live(self.ui.refresh(), refresh_per_second=0.1) as live:
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/ui.py", line 58, in refresh
    return self.layout(self.base_layout(), self.layout_params).load(self.data_loader.fetch_data())
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/plugins/ecs/service/layouts.py", line 141, in load
    self.base_layout["main_right_top_memory"].update(self.memory())
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/plugins/ecs/service/layouts.py", line 85, in memory
    AsciiPlotIntegration(self.data.fetcher["cloudwatch_memory_data"])
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/lucyna/ui.py", line 70, in __init__
    chart = asciiize(y_values, inter_points_margin=4, x_ticks=x_ticks)
TypeError: asciiize() got an unexpected keyword argument 'x_ticks'
```

**Comment by richstokes** [comment]
see https://github.com/epsylabs/lucyna/pull/2
